embedding_path: /lustre/groups/ml01/workspace/xiaotong.fu/data/pancellflow/sup/drug_embeddings_256d.pkl
output_dir: /lustre/groups/ml01/workspace/xiaotong.fu/data/pancellflow/unipert

# Drug names in this set are mapped to "control" (case-insensitive)
control_aliases:
  - control
  - vehicle
  - dmso_tf
  - unperturbed
  - none
  - nan

datasets:
  - path: /lustre/groups/ml01/workspace/xiaotong.fu/data/pancellflow/unipert/tahoe_sw48_w_emb.h5ad
    drug_col: drug

  - path: /lustre/groups/ml01/workspace/xiaotong.fu/data/pancellflow/unipert/tahoe_h4_w_emb.h5ad
    drug_col: drug

  - path: /lustre/groups/ml01/workspace/xiaotong.fu/data/pancellflow/unipert/tahoe_snu_1_w_emb.h5ad
    drug_col: drug
